# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        recommendation: 1
        ViT: 2
        vital: -2
        vitamin: -2
        micro kernel: 1
        micro VM: 1
        recipes: 1
        NoSQL: 1
        relational model: 1
        image captioning: 2
        video captioning: 3
        personalize: 2
        navigation: 2


# 通知の閾値
score_threshold: 2
