# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 1
        resnet: 1
        anomaly detection: 1
        recommend: 1
        GPT-3: 1
        transformer: 1
        attention: 1
        micro kernel: 1
        recipe: 1

# 通知の閾値
score_threshold: 0
